### ISSUE TITLE
The chat icon keeps flashing even after you have answered

### ISSUE THREAD

**Issue by sferoze** [vivekvrao/user-feedback#1]
The chat text keeps flashing red/blue even after you have answered. Cannot get it to stop.

**Comment by vivekvrao** [comment]
thanks for pointing out the issue. Clicking on the Highlighted user name/email on the right - should mark that chat as cleared - and when all chats are cleared - the blinking get disabled.

I've added logic to the plugin so that - sending a response would also clear the flashing. 
The update contains a few additional things - like using images for feedback/chat positioning
and allowing user to use email address for specifying moderator instead of userId.

Please verify that your issue is resolved - in this version or in the upgrade.
thanks,

**Comment by vivekvrao** [comment]
resolved with new version.
